EDA

In [284]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

train = pd.read_csv('../data/raw/train_v2.csv')
members = pd.read_csv('../data/raw/members_v3.csv')

In [285]:
train.head()

                                           msno  is_churn
0  ugx0CjOMzazClkFzU2xasmDZaoIqOUAZPsH1q0teWCg=         1
1  f/NmvEzHfhINFEYZTR05prUdr+E+3+oewvweYz9cCQE=         1
2  zLo9f73nGGT1p21ltZC3ChiRnAVvgibMyazbCxvWPcg=         1
3  8iF/+8HY8lJKFrTc7iR9ZYGCG2Ecrogbc2Vy5YhsfhQ=         1
4  K6fja4+jmoZ5xG6BypqX80Uw/XKpMgrEMdG2edFOxnA=         1

In [286]:
print(train.shape)
print(members.shape)

(970960, 2)
(6769473, 6)

In [287]:
members.head()

,msno,city,bd,gender,registered_via,registration_init_time
0,Rb9UwLQTrxzBVwCB6+bCcSQWZ9JiNLC9dXtM1oEsZA8=,1,0,NaN,11,20110911
1,+tJonkh+O1CA796Fm5X60UMOtB6POHAwPjbTRVl/EuU=,1,0,NaN,7,20110914
2,cV358ssn7a0f7jZOwGNWS07wCKVqxyiImJUX6xcIwKw=,1,0,NaN,11,20110915
3,9bzDeJP6sQodK73K5CBlJ6fgIQzPeLnRl0p5B77XP+g=,1,0,NaN,11,20110915
4,WFLY3s7z4EZsieHCt63XrsdtfTEmJ+2PnnKLH5GY4Tk=,6,32,female,9,20110915

In [288]:
members.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6769473 entries, 0 to 6769472
Data columns (total 6 columns):
 #   Column                  Dtype
---  ------                  -----
 0   msno                    object
 1   city                    int64
 2   bd                      int64
 3   gender                  object
 4   registered_via          int64
 5   registration_init_time  int64
dtypes: int64(4), object(2)
memory usage: 309.9+ MB

In [289]:
members['registration_init_time'] = pd.to_datetime(members['registration_init_time'], format='%Y%m%d')

In [290]:
members.describe(include='all')

,msno,city,bd,gender,registered_via,registration_init_time
count,6769473,6.769473e+06,6.769473e+06,2339968,6.769473e+06,6769473
unique,6769473,NaN,NaN,2,NaN,NaN
top,isBt+JlgvZRNy6lxVr5vvuJ4lD00ofTaKyJ+uRnGcPg=,NaN,NaN,male,NaN,NaN
freq,1,NaN,NaN,1195355,NaN,NaN
mean,NaN,3.847358e+00,9.795794e+00,NaN,5.253069e+00,2014-12-13 21:10:12.902246144
min,NaN,1.000000e+00,-7.168000e+03,NaN,-1.000000e+00,2004-03-26 00:00:00
25%,NaN,1.000000e+00,0.000000e+00,NaN,4.000000e+00,2014-04-22 00:00:00
50%,NaN,1.000000e+00,0.000000e+00,NaN,4.000000e+00,2015-10-10 00:00:00
75%,NaN,4.000000e+00,2.100000e+01,NaN,7.000000e+00,2016-06-04 00:00:00
max,NaN,2.200000e+01,2.016000e+03,NaN,1.900000e+01,2017-04-29 00:00:00
std,NaN,5.478359e+00,1.792590e+01,NaN,2.361398e+00,NaN

In [291]:
print(members[members['bd'] < 18])

                                                 msno  city  bd gender  \
0        Rb9UwLQTrxzBVwCB6+bCcSQWZ9JiNLC9dXtM1oEsZA8=     1   0    NaN
1        +tJonkh+O1CA796Fm5X60UMOtB6POHAwPjbTRVl/EuU=     1   0    NaN
2        cV358ssn7a0f7jZOwGNWS07wCKVqxyiImJUX6xcIwKw=     1   0    NaN
3        9bzDeJP6sQodK73K5CBlJ6fgIQzPeLnRl0p5B77XP+g=     1   0    NaN
6        jNCGK78YkTyId3H3wFavcBLDmz7pfqlvCfUKf4G1Lw4=     1   0    NaN
...                                               ...   ...  ..    ...
6769466  O11rAa17ANM6DGMMVb9L2vwCQFv/S6SR3SDB1nGuOAc=     1   0    NaN
6769468  VSGkb3hyBRUtb/b1MQUZbvOkktS3vKLnhMHW0CF8eyU=     1   0    NaN
6769469  nWjH7glPkZ7jOVaCRwwjlpmp0T1hSWdv8hMJxiWCwKc=     1   0    NaN
6769471  XVlwT3fdCFGKqerEKBzUIjK+jzI6jzSke4cDMVhYyjE=     1   0    NaN
6769472  isBt+JlgvZRNy6lxVr5vvuJ4lD00ofTaKyJ+uRnGcPg=     1   0    NaN

         registered_via registration_init_time
0                    11             2011-09-11
1                     7             2011-09-14
2                    11             2011-09-15
3                    11             2011-09-15
6                     7             2011-09-16
...                 ...                    ...
6769466               7             2015-10-20
6769468               7             2015-10-20
6769469               7             2015-10-20
6769471               4             2015-10-20
6769472               4             2015-10-21

[4689746 rows x 6 columns]

In [292]:
print(members['registered_via'].value_counts())

registered_via
 4     2793213
 3     1643208
 9     1482863
 7      805895
 11      25047
 13       5455
 8        3982
 5        3115
 17       1494
 2        1452
 6        1213
 19        974
 16        888
 14        615
 1          43
 10         10
 18          5
-1           1
Name: count, dtype: int64

In [293]:
base = train.merge(members, on="msno", how="left")

In [294]:
base.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 970960 entries, 0 to 970959
Data columns (total 7 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   msno                    970960 non-null  object
 1   is_churn                970960 non-null  int64
 2   city                    860967 non-null  float64
 3   bd                      860967 non-null  float64
 4   gender                  388905 non-null  object
 5   registered_via          860967 non-null  float64
 6   registration_init_time  860967 non-null  datetime64[ns]
dtypes: datetime64[ns](1), float64(3), int64(1), object(2)
memory usage: 51.9+ MB

In [295]:
base.describe(include='all')

,msno,is_churn,city,bd,gender,registered_via,registration_init_time
count,970960,970960.000000,860967.000000,860967.000000,388905,860967.000000,860967
unique,970960,NaN,NaN,NaN,2,NaN,NaN
top,Zkuhc7S+hhMgLkKft6lfrsyi2XHDo6WH7QDdXlringE=,NaN,NaN,NaN,male,NaN,NaN
freq,1,NaN,NaN,NaN,204561,NaN,NaN
mean,NaN,0.089942,5.937295,13.583854,NaN,6.892744,2013-09-13 07:10:23.952834560
min,NaN,0.000000,1.000000,-3152.000000,NaN,3.000000,2004-03-26 00:00:00
25%,NaN,0.000000,1.000000,0.000000,NaN,7.000000,2012-02-14 00:00:00
50%,NaN,0.000000,1.000000,0.000000,NaN,7.000000,2014-06-02 00:00:00
75%,NaN,0.000000,13.000000,27.000000,NaN,9.000000,2016-01-18 00:00:00
max,NaN,1.000000,22.000000,2016.000000,NaN,13.000000,2017-04-24 00:00:00
std,NaN,0.286099,6.441203,20.064040,NaN,1.937794,NaN

In [296]:
base.nunique()

msno                      970960
is_churn                       2
city                          21
bd                           231
gender                         2
registered_via                 5
registration_init_time      4749
dtype: int64

In [297]:
transactions = pd.read_csv('./data/transactions_v2.csv')
transactions.head()

,msno,payment_method_id,payment_plan_days,plan_list_price,actual_amount_paid,is_auto_renew,transaction_date,membership_expire_date,is_cancel
0,++6eU4LsQ3UQ20ILS7d99XK8WbiVgbyYL4FUgzZR134=,32,90,298,298,0,20170131,20170504,0
1,++lvGPJOinuin/8esghpnqdljm6NXS8m8Zwchc7gOeA=,41,30,149,149,1,20150809,20190412,0
2,+/GXNtXWQVfKrEDqYAzcSw2xSPYMKWNj22m+5XkVQZc=,36,30,180,180,1,20170303,20170422,0
3,+/w1UrZwyka4C9oNH3+Q8fUf3fD8R3EwWrx57ODIsqk=,36,30,180,180,1,20170329,20170331,1
4,+00PGzKTYqtnb65mPKPyeHXcZEwqiEzktpQksaaSC3c=,41,30,99,99,1,20170323,20170423,0

In [298]:
print(transactions['msno'].nunique())

1197050

In [299]:
print(transactions.shape)
transactions.info()
transactions.describe(include='all')

(1431009, 9)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1431009 entries, 0 to 1431008
Data columns (total 9 columns):
 #   Column                  Non-Null Count    Dtype
---  ------                  --------------    -----
 0   msno                    1431009 non-null  object
 1   payment_method_id       1431009 non-null  int64
 2   payment_plan_days       1431009 non-null  int64
 3   plan_list_price         1431009 non-null  int64
 4   actual_amount_paid      1431009 non-null  int64
 5   is_auto_renew           1431009 non-null  int64
 6   transaction_date        1431009 non-null  int64
 7   membership_expire_date  1431009 non-null  int64
 8   is_cancel               1431009 non-null  int64
dtypes: int64(8), object(1)
memory usage: 98.3+ MB

,msno,payment_method_id,payment_plan_days,plan_list_price,actual_amount_paid,is_auto_renew,transaction_date,membership_expire_date,is_cancel
count,1431009,1.431009e+06,1.431009e+06,1.431009e+06,1.431009e+06,1.431009e+06,1.431009e+06,1.431009e+06,1.431009e+06
unique,1197050,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,72gJqt1O31E/WoxAEYFn9LHNI6mAZFGera5Q6gvsFkA=,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,208,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,3.791835e+01,6.601770e+01,2.817870e+02,2.813172e+02,7.853025e-01,2.016848e+07,2.017110e+07,2.455121e-02
std,NaN,4.964805e+00,1.024864e+02,4.351861e+02,4.354200e+02,4.106124e-01,4.858797e+03,3.032367e+03,1.547529e-01
min,NaN,2.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,2.015010e+07,2.016042e+07,0.000000e+00
25%,NaN,3.600000e+01,3.000000e+01,9.900000e+01,9.900000e+01,1.000000e+00,2.017023e+07,2.017041e+07,0.000000e+00
50%,NaN,4.000000e+01,3.000000e+01,1.490000e+02,1.490000e+02,1.000000e+00,2.017031e+07,2.017042e+07,0.000000e+00
75%,NaN,4.100000e+01,3.000000e+01,1.490000e+02,1.490000e+02,1.000000e+00,2.017032e+07,2.017050e+07,0.000000e+00
max,NaN,4.100000e+01,4.500000e+02,2.000000e+03,2.000000e+03,1.000000e+00,2.017033e+07,2.036102e+07,1.000000e+00

In [300]:
col = ['transaction_date', 'membership_expire_date']
transactions[col] = transactions[col].apply(lambda x: pd.to_datetime(x, format='%Y%m%d'))
transactions.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1431009 entries, 0 to 1431008
Data columns (total 9 columns):
 #   Column                  Non-Null Count    Dtype
---  ------                  --------------    -----
 0   msno                    1431009 non-null  object
 1   payment_method_id       1431009 non-null  int64
 2   payment_plan_days       1431009 non-null  int64
 3   plan_list_price         1431009 non-null  int64
 4   actual_amount_paid      1431009 non-null  int64
 5   is_auto_renew           1431009 non-null  int64
 6   transaction_date        1431009 non-null  datetime64[ns]
 7   membership_expire_date  1431009 non-null  datetime64[ns]
 8   is_cancel               1431009 non-null  int64
dtypes: datetime64[ns](2), int64(6), object(1)
memory usage: 98.3+ MB

In [ ]:
# Tomamos solo usuarios del train
train_users = set(train["msno"])

train_txn = transactions[transactions["msno"].isin(train_users)].copy()

# Para cada usuario, tomamos su última expiración conocida
user_cutoff = (
    train_txn
    .groupby("msno")["membership_expire_date"]
    .max()
    .rename("cutoff_date")
    .reset_index()
)

print(user_cutoff.shape)
print(user_cutoff.head())
print(user_cutoff["msno"].nunique())

(933578, 2)
                                           msno cutoff_date
0  +++hVY1rZox/33YtvDgmKA2Frg/2qhkz12B9ylCvh8o=  2017-04-15
1  +++l/EXNMLTijfLBa8p2TUVVVp2aFGSuUI/h7mLmthw=  2017-05-19
2  +++snpr7pmobhLKUgSHTv/mpkqgBT0tQJ0zQj6qKrqc=  2017-04-26
3  ++/9R3sX37CjxbY/AaGvbwr3QkwElKBCtSvVzhCBDOk=  2017-04-15
4  ++/UDNo9DLrxT8QVGiDi1OnWfczAdEwThaVyD0fXO50=  2017-05-23
933578

In [245]:
transactions["payment_method_id"] = transactions["payment_method_id"].astype("int16")
transactions["payment_plan_days"] = transactions["payment_plan_days"].astype("int16")
transactions["plan_list_price"] = transactions["plan_list_price"].astype("int32")
transactions["is_cancel"] = transactions["is_cancel"].astype("int8")
transactions["is_auto_renew"] = transactions["is_auto_renew"].astype("int8")

In [246]:
txn_valid = transactions[transactions["is_cancel"] == 0]

In [247]:
txn_count = transactions.groupby("msno").size().rename("txn_count")
txn_count.head()
print(txn_count.max())

208

In [248]:
valid_txn_count = txn_valid.groupby("msno").size().rename("valid_txn_count")

In [249]:
print(transactions['msno'].nunique())

1197050

In [250]:
last_txn = txn_valid.groupby("msno")["transaction_date"].max()
last_txn.head()

msno
+++IZseRRiQS9aaSkH6cMYU6bGDcxUieAi/tH67sC5s=   2016-10-23
+++hVY1rZox/33YtvDgmKA2Frg/2qhkz12B9ylCvh8o=   2017-03-15
+++l/EXNMLTijfLBa8p2TUVVVp2aFGSuUI/h7mLmthw=   2017-03-31
+++snpr7pmobhLKUgSHTv/mpkqgBT0tQJ0zQj6qKrqc=   2017-03-26
++/9R3sX37CjxbY/AaGvbwr3QkwElKBCtSvVzhCBDOk=   2017-03-15
Name: transaction_date, dtype: datetime64[ns]

In [251]:
recency = (cutoff_date - last_txn).dt.days.rename("txn_recency_days")
recency.head()

msno
+++IZseRRiQS9aaSkH6cMYU6bGDcxUieAi/tH67sC5s=    128
+++hVY1rZox/33YtvDgmKA2Frg/2qhkz12B9ylCvh8o=    -15
+++l/EXNMLTijfLBa8p2TUVVVp2aFGSuUI/h7mLmthw=    -31
+++snpr7pmobhLKUgSHTv/mpkqgBT0tQJ0zQj6qKrqc=    -26
++/9R3sX37CjxbY/AaGvbwr3QkwElKBCtSvVzhCBDOk=    -15
Name: txn_recency_days, dtype: int64

In [252]:
cancel_count = transactions.groupby("msno")["is_cancel"].sum().rename("cancel_count")
has_cancelled = (cancel_count > 0).astype(int).rename("has_cancelled")
print(cancel_count.head())
print(has_cancelled.head())
print(transactions['is_cancel'].value_counts())

msno
+++IZseRRiQS9aaSkH6cMYU6bGDcxUieAi/tH67sC5s=    0
+++hVY1rZox/33YtvDgmKA2Frg/2qhkz12B9ylCvh8o=    0
+++l/EXNMLTijfLBa8p2TUVVVp2aFGSuUI/h7mLmthw=    0
+++snpr7pmobhLKUgSHTv/mpkqgBT0tQJ0zQj6qKrqc=    0
++/9R3sX37CjxbY/AaGvbwr3QkwElKBCtSvVzhCBDOk=    0
Name: cancel_count, dtype: int8
msno
+++IZseRRiQS9aaSkH6cMYU6bGDcxUieAi/tH67sC5s=    0
+++hVY1rZox/33YtvDgmKA2Frg/2qhkz12B9ylCvh8o=    0
+++l/EXNMLTijfLBa8p2TUVVVp2aFGSuUI/h7mLmthw=    0
+++snpr7pmobhLKUgSHTv/mpkqgBT0tQJ0zQj6qKrqc=    0
++/9R3sX37CjxbY/AaGvbwr3QkwElKBCtSvVzhCBDOk=    0
Name: has_cancelled, dtype: int64
is_cancel
0    1395876
1      35133
Name: count, dtype: int64

In [253]:
cancel_ratio = (cancel_count / txn_count).rename("cancel_ratio")

In [254]:
print(cancel_count.value_counts())

cancel_count
0    1162499
1      34014
2        507
3         22
4          4
5          3
8          1
Name: count, dtype: int64

In [255]:
print(transactions['is_auto_renew'].value_counts())

is_auto_renew
1    1123775
0     307234
Name: count, dtype: int64

In [256]:
auto_renew_count = transactions.groupby("msno")["is_auto_renew"].sum().rename("auto_renew_count")
has_auto_renew = (auto_renew_count > 0).astype(int).rename("has_auto_renew")
print(auto_renew_count.head())

msno
+++IZseRRiQS9aaSkH6cMYU6bGDcxUieAi/tH67sC5s=    0
+++hVY1rZox/33YtvDgmKA2Frg/2qhkz12B9ylCvh8o=    1
+++l/EXNMLTijfLBa8p2TUVVVp2aFGSuUI/h7mLmthw=    2
+++snpr7pmobhLKUgSHTv/mpkqgBT0tQJ0zQj6qKrqc=    1
++/9R3sX37CjxbY/AaGvbwr3QkwElKBCtSvVzhCBDOk=    1
Name: auto_renew_count, dtype: int8

In [257]:
print(auto_renew_count.value_counts())

auto_renew_count
1     805646
0     273237
2     102277
3       7204
4       1625
5       1515
6        776
7        582
8        429
11       355
9        339
10       287
13       281
12       279
21       274
14       259
15       211
16       156
20       155
17       118
19       113
22       108
23        85
24        68
18        62
25        58
36        57
35        50
28        47
29        44
37        40
27        40
26        38
32        38
33        37
34        36
31        36
30        33
38        16
39         7
45         7
46         6
48         6
47         3
40         2
41         2
43         1
65         1
61         1
49         1
42         1
44         1
Name: count, dtype: int64

In [258]:
plan_days_median = txn_valid.groupby("msno")["payment_plan_days"].median().rename("plan_days_median")
print(plan_days_median.head())
print(plan_days_median.value_counts())

msno
+++IZseRRiQS9aaSkH6cMYU6bGDcxUieAi/tH67sC5s=    395.0
+++hVY1rZox/33YtvDgmKA2Frg/2qhkz12B9ylCvh8o=     30.0
+++l/EXNMLTijfLBa8p2TUVVVp2aFGSuUI/h7mLmthw=     30.0
+++snpr7pmobhLKUgSHTv/mpkqgBT0tQJ0zQj6qKrqc=     30.0
++/9R3sX37CjxbY/AaGvbwr3QkwElKBCtSvVzhCBDOk=     30.0
Name: plan_days_median, dtype: float64
plan_days_median
30.0     998958
410.0     78088
195.0     26093
180.0     22204
90.0      13414
          ...
275.0         1
101.5         1
228.5         1
232.5         1
272.5         1
Name: count, Length: 139, dtype: int64

In [259]:
last_plan_days = txn_valid.sort_values("transaction_date") \
    .groupby("msno")["payment_plan_days"] \
    .last().rename("last_plan_days")

print(last_plan_days.head())
print(last_plan_days.value_counts())

msno
+++IZseRRiQS9aaSkH6cMYU6bGDcxUieAi/tH67sC5s=    395
+++hVY1rZox/33YtvDgmKA2Frg/2qhkz12B9ylCvh8o=     30
+++l/EXNMLTijfLBa8p2TUVVVp2aFGSuUI/h7mLmthw=     30
+++snpr7pmobhLKUgSHTv/mpkqgBT0tQJ0zQj6qKrqc=     30
++/9R3sX37CjxbY/AaGvbwr3QkwElKBCtSvVzhCBDOk=     30
Name: last_plan_days, dtype: int16
last_plan_days
30     999426
410     78449
195     26285
180     23545
90      15345
395      9519
7        7624
360      4313
100      3945
365      3663
415      3277
200      2929
120      1858
400      1759
450      1721
270       977
60        930
240       383
1         375
10        100
14         67
45         40
70         39
80         34
230        28
0          23
110        11
35          5
3           3
21          1
Name: count, dtype: int64

In [260]:
avg_price = txn_valid.groupby("msno")["plan_list_price"].mean().rename("avg_plan_price")
print(avg_price.head())
print(avg_price.value_counts())

msno
+++IZseRRiQS9aaSkH6cMYU6bGDcxUieAi/tH67sC5s=    1599.0
+++hVY1rZox/33YtvDgmKA2Frg/2qhkz12B9ylCvh8o=      99.0
+++l/EXNMLTijfLBa8p2TUVVVp2aFGSuUI/h7mLmthw=     149.0
+++snpr7pmobhLKUgSHTv/mpkqgBT0tQJ0zQj6qKrqc=     149.0
++/9R3sX37CjxbY/AaGvbwr3QkwElKBCtSvVzhCBDOk=     149.0
Name: avg_plan_price, dtype: float64
avg_plan_price
149.000000     425873
99.000000      385374
180.000000      99374
1788.000000     79810
100.000000      40733
                ...
121.583333          1
136.647059          1
139.724138          1
269.250000          1
186.531250          1
Name: count, Length: 1576, dtype: int64

In [261]:
txn_features = pd.concat([
    txn_count,
    valid_txn_count,
    recency,
    cancel_count,
    has_cancelled,
    auto_renew_count,
    has_auto_renew,
    plan_days_median,
    last_plan_days,
    avg_price,
], axis=1).reset_index()

In [262]:
print(txn_features.head().to_string())
print(txn_features.shape)

                                           msno  txn_count  valid_txn_count  txn_recency_days  cancel_count  has_cancelled  auto_renew_count  has_auto_renew  plan_days_median  last_plan_days  avg_plan_price
0  +++IZseRRiQS9aaSkH6cMYU6bGDcxUieAi/tH67sC5s=          1              1.0             128.0             0              0                 0               0             395.0           395.0          1599.0
1  +++hVY1rZox/33YtvDgmKA2Frg/2qhkz12B9ylCvh8o=          1              1.0             -15.0             0              0                 1               1              30.0            30.0            99.0
2  +++l/EXNMLTijfLBa8p2TUVVVp2aFGSuUI/h7mLmthw=          2              2.0             -31.0             0              0                 2               1              30.0            30.0           149.0
3  +++snpr7pmobhLKUgSHTv/mpkqgBT0tQJ0zQj6qKrqc=          1              1.0             -26.0             0              0                 1               1              30.0            30.0           149.0
4  ++/9R3sX37CjxbY/AaGvbwr3QkwElKBCtSvVzhCBDOk=          1              1.0             -15.0             0              0                 1               1              30.0            30.0           149.0
(1197050, 11)

In [263]:
print(base.head().to_string())

                                           msno  is_churn  city    bd  gender  registered_via registration_init_time
0  ugx0CjOMzazClkFzU2xasmDZaoIqOUAZPsH1q0teWCg=         1   5.0  28.0    male             3.0             2013-12-23
1  f/NmvEzHfhINFEYZTR05prUdr+E+3+oewvweYz9cCQE=         1  13.0  20.0    male             3.0             2013-12-23
2  zLo9f73nGGT1p21ltZC3ChiRnAVvgibMyazbCxvWPcg=         1  13.0  18.0    male             3.0             2013-12-27
3  8iF/+8HY8lJKFrTc7iR9ZYGCG2Ecrogbc2Vy5YhsfhQ=         1   1.0   0.0     NaN             7.0             2014-01-09
4  K6fja4+jmoZ5xG6BypqX80Uw/XKpMgrEMdG2edFOxnA=         1  13.0  35.0  female             7.0             2014-01-25

In [264]:
print(base['msno'].nunique())

970960

In [265]:
df = base.merge(txn_features, on="msno", how="left")

In [162]:
print(df.head().to_string())
print(df.shape)
df.info()
print(df.describe(include='all').to_string())
print(df.nunique())

                                           msno  is_churn  city    bd  gender  registered_via registration_init_time  txn_count  valid_txn_count  txn_recency_days  cancel_count  has_cancelled  auto_renew_count  has_auto_renew  plan_days_median  last_plan_days  avg_plan_price last_expire_date
0  ugx0CjOMzazClkFzU2xasmDZaoIqOUAZPsH1q0teWCg=         1   5.0  28.0    male             3.0             2013-12-23        NaN              NaN               NaN           NaN            NaN               NaN             NaN               NaN             NaN             NaN              NaT
1  f/NmvEzHfhINFEYZTR05prUdr+E+3+oewvweYz9cCQE=         1  13.0  20.0    male             3.0             2013-12-23        NaN              NaN               NaN           NaN            NaN               NaN             NaN               NaN             NaN             NaN              NaT
2  zLo9f73nGGT1p21ltZC3ChiRnAVvgibMyazbCxvWPcg=         1  13.0  18.0    male             3.0             2013-12-27        NaN              NaN               NaN           NaN            NaN               NaN             NaN               NaN             NaN             NaN              NaT
3  8iF/+8HY8lJKFrTc7iR9ZYGCG2Ecrogbc2Vy5YhsfhQ=         1   1.0   0.0     NaN             7.0             2014-01-09       10.0             10.0             448.0           0.0            0.0              10.0             1.0              30.0            30.0           149.0       2018-01-08
4  K6fja4+jmoZ5xG6BypqX80Uw/XKpMgrEMdG2edFOxnA=         1  13.0  35.0  female             7.0             2014-01-25        7.0              6.0              12.0           1.0            1.0               7.0             1.0              30.0            30.0            99.0       2017-08-18
(970960, 18)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 970960 entries, 0 to 970959
Data columns (total 18 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   msno                    970960 non-null  object
 1   is_churn                970960 non-null  int64
 2   city                    860967 non-null  float64
 3   bd                      860967 non-null  float64
 4   gender                  388905 non-null  object
 5   registered_via          860967 non-null  float64
 6   registration_init_time  860967 non-null  datetime64[ns]
 7   txn_count               92686 non-null   float64
 8   valid_txn_count         92682 non-null   float64
 9   txn_recency_days        92686 non-null   float64
 10  cancel_count            92686 non-null   float64
 11  has_cancelled           92686 non-null   float64
 12  auto_renew_count        92686 non-null   float64
 13  has_auto_renew          92686 non-null   float64
 14  plan_days_median        92682 non-null   float64
 15  last_plan_days          92682 non-null   float64
 16  avg_plan_price          92682 non-null   float64
 17  last_expire_date        92682 non-null   datetime64[ns]
dtypes: datetime64[ns](2), float64(13), int64(1), object(2)
memory usage: 133.3+ MB
                                                msno       is_churn           city             bd  gender  registered_via         registration_init_time     txn_count  valid_txn_count  txn_recency_days  cancel_count  has_cancelled  auto_renew_count  has_auto_renew  plan_days_median  last_plan_days  avg_plan_price               last_expire_date
count                                         970960  970960.000000  860967.000000  860967.000000  388905   860967.000000                         860967  92686.000000     92682.000000      92686.000000  92686.000000   92686.000000      92686.000000    92686.000000      92682.000000    92682.000000    92682.000000                          92682
unique                                        970960            NaN            NaN            NaN       2             NaN                            NaN           NaN              NaN               NaN           NaN            NaN               NaN             NaN               NaN             NaN             NaN                            NaN
top     Zkuhc7S+hhMgLkKft6lfrsyi2XHDo6WH7QDdXlringE=            NaN            NaN            NaN    male             NaN                            NaN           NaN              NaN               NaN           NaN            NaN               NaN             NaN               NaN             NaN             NaN                            NaN
freq                                               1            NaN            NaN            NaN  204561             NaN                            NaN           NaN              NaN               NaN           NaN            NaN               NaN             NaN               NaN             NaN             NaN                            NaN
mean                                             NaN       0.089942       5.937295      13.583854     NaN        6.892744  2013-09-13 07:10:23.952834560      1.835574         1.811528         36.047569      0.024124       0.020014          1.728406        0.943638         34.487700       34.646091      164.893084  2017-05-14 07:59:06.863468544
min                                              NaN       0.000000       1.000000   -3152.000000     NaN        3.000000            2004-03-26 00:00:00      1.000000         1.000000          0.000000      0.000000       0.000000          0.000000        0.000000          0.000000        0.000000        0.000000            2017-04-01 00:00:00
25%                                              NaN       0.000000       1.000000       0.000000     NaN        7.000000            2012-02-14 00:00:00      1.000000         1.000000          0.000000      0.000000       0.000000          1.000000        1.000000         30.000000       30.000000      149.000000            2017-04-09 00:00:00
50%                                              NaN       0.000000       1.000000       0.000000     NaN        7.000000            2014-06-02 00:00:00      1.000000         1.000000          0.000000      0.000000       0.000000          1.000000        1.000000         30.000000       30.000000      149.000000            2017-04-18 00:00:00
75%                                              NaN       0.000000      13.000000      27.000000     NaN        9.000000            2016-01-18 00:00:00      1.000000         1.000000          0.000000      0.000000       0.000000          1.000000        1.000000         30.000000       30.000000      149.000000            2017-04-27 00:00:00
max                                              NaN       1.000000      22.000000    2016.000000     NaN       13.000000            2017-04-24 00:00:00    208.000000       208.000000        788.000000      8.000000       1.000000         65.000000        1.000000        450.000000      450.000000     2000.000000            2023-08-17 00:00:00
std                                              NaN       0.286099       6.441203      20.064040     NaN        1.937794                            NaN      3.680769         3.603164        114.564543      0.181524       0.140048          3.370109        0.230621         35.811416       37.252088      145.618249                            NaN
msno                      970960
is_churn                       2
city                          21
bd                           231
gender                         2
registered_via                 5
registration_init_time      4749
txn_count                     62
valid_txn_count               58
txn_recency_days             394
cancel_count                   7
has_cancelled                  2
auto_renew_count              50
has_auto_renew                 2
plan_days_median              59
last_plan_days                27
avg_plan_price               861
last_expire_date            1009
dtype: int64