In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

logs = pd.read_csv('../data/raw/user_logs_v2.csv')

In [3]:
logs.head()

,msno,date,num_25,num_50,num_75,num_985,num_100,num_unq,total_secs
0,u9E91QDTvHLq6NXjEaWv8u4QIqhrHk72kE+w31Gnhdg=,20170331,8,4,0,1,21,18,6309.273
1,nTeWW/eOZA/UHKdD5L7DEqKKFTjaAj3ALLPoAWsU8n0=,20170330,2,2,1,0,9,11,2390.699
2,2UqkWXwZbIjs03dHLU9KHJNNEvEkZVzm69f3jCS+uLI=,20170331,52,3,5,3,84,110,23203.337
3,ycwLc+m2O0a85jSLALtr941AaZt9ai8Qwlg9n0Nql5U=,20170331,176,4,2,2,19,191,7100.454
4,EGcbTofOSOkMmQyN1NMLxHEXJ1yV3t/JdhGwQ9wXjnI=,20170331,2,1,0,1,112,93,28401.558

In [4]:
logs['date'] = pd.to_datetime(logs['date'], format='%Y%m%d')

In [5]:
logs.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18396362 entries, 0 to 18396361
Data columns (total 9 columns):
 #   Column      Dtype
---  ------      -----
 0   msno        object
 1   date        datetime64[ns]
 2   num_25      int64
 3   num_50      int64
 4   num_75      int64
 5   num_985     int64
 6   num_100     int64
 7   num_unq     int64
 8   total_secs  float64
dtypes: datetime64[ns](1), float64(1), int64(6), object(1)
memory usage: 1.2+ GB

In [7]:
logs.shape

(18396362, 9)

In [6]:
logs.describe(include='all')

,msno,date,num_25,num_50,num_75,num_985,num_100,num_unq,total_secs
count,18396362,18396362,1.839636e+07,1.839636e+07,1.839636e+07,1.839636e+07,1.839636e+07,1.839636e+07,1.839636e+07
unique,1103894,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,b74Xot5HcOL8YQGiuwLw+Cm7RyGV2fOkGczJomGLocg=,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,2017-03-16 02:03:16.931544832,6.191401e+00,1.508789e+00,9.413759e-01,1.079905e+00,3.028246e+01,2.903615e+01,7.904814e+03
min,NaN,2017-03-01 00:00:00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00,1.000000e-03
25%,NaN,2017-03-08 00:00:00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,7.000000e+00,8.000000e+00,1.959944e+03
50%,NaN,2017-03-16 00:00:00,2.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,1.700000e+01,1.800000e+01,4.582990e+03
75%,NaN,2017-03-24 00:00:00,7.000000e+00,2.000000e+00,1.000000e+00,1.000000e+00,3.700000e+01,3.800000e+01,9.848441e+03
max,NaN,2017-03-31 00:00:00,5.639000e+03,9.120000e+02,5.080000e+02,1.561000e+03,4.110700e+04,4.925000e+03,9.194059e+06
std,NaN,NaN,1.342827e+01,3.908539e+00,1.924840e+00,3.518409e+00,4.203641e+01,3.219866e+01,1.013632e+04